name: Publish Python distributions to PyPI

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
  release:
    types:
      - published
jobs:
  build_wheels:
    name: Build wheels [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.11
        os:
          - ubuntu-24.04

    steps:
      # We do not release exactly the 1.2.1 tag as we need 
      # to actually release on urdfdom-py
      - uses: actions/checkout@v4
        with:
          repository: 'ros/urdf_parser_py'
          ref: '492223ce830cafc4dc2dcd98b82bb0eb91511118'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pypa/build
        run: pip install build

      - name: Build wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-24.04
    needs: [build_wheels]
    if: startsWith(github.ref, 'refs/tags')
    environment:
      name: release
      url: https://test.pypi.org/p/urdfdom-py
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy
          verbose: true
